/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/base/AppHeader.vue')['default']
    CurseForge: typeof import('./src/components/home/logo/CurseForge.vue')['default']
    Global: typeof import('./src/components/base/Global.vue')['default']
    LeftMenu: typeof import('./src/components/base/LeftMenu.vue')['default']
    ModIo: typeof import('./src/components/home/logo/ModIo.vue')['default']
    NexusMods: typeof import('./src/components/home/logo/NexusMods.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sponsor: typeof import('./src/components/home/Sponsor.vue')['default']
    Thunderstore: typeof import('./src/components/home/logo/Thunderstore.vue')['default']
    Welcome: typeof import('./src/components/home/Welcome.vue')['default']
  }
}
